spring:
  config:
    import: optional:file:.env[.properties],optional:file:.env.local[.properties]

  application:
    name: VeagleSpaceTech

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

veagle:
  mail:
    smtp:
      host: ${MAIL_HOST}
      port: ${MAIL_PORT}
      ssl-trust: ${MAIL_SSL_TRUST:${MAIL_HOST}}

    otp:
      - email: ${OTP_MAIL_1_EMAIL}
        password: ${OTP_MAIL_1_PASSWORD}
      - email: ${OTP_MAIL_2_EMAIL}
        password: ${OTP_MAIL_2_PASSWORD}
      - email: ${OTP_MAIL_3_EMAIL}
        password: ${OTP_MAIL_3_PASSWORD}

    careers:
      - email: ${CAREERS_MAIL_1_EMAIL}
        password: ${CAREERS_MAIL_1_PASSWORD}
      - email: ${CAREERS_MAIL_2_EMAIL}
        password: ${CAREERS_MAIL_2_PASSWORD}
      - email: ${CAREERS_MAIL_3_EMAIL}
        password: ${CAREERS_MAIL_3_PASSWORD}
      - email: ${CAREERS_MAIL_4_EMAIL}
        password: ${CAREERS_MAIL_4_PASSWORD}

    support:
      - email: ${SUPPORT_MAIL_1_EMAIL}
        password: ${SUPPORT_MAIL_1_PASSWORD}
      - email: ${SUPPORT_MAIL_2_EMAIL}
        password: ${SUPPORT_MAIL_2_PASSWORD}
      - email: ${SUPPORT_MAIL_3_EMAIL}
        password: ${SUPPORT_MAIL_3_PASSWORD}
      - email: ${SUPPORT_MAIL_4_EMAIL}
        password: ${SUPPORT_MAIL_4_PASSWORD}
      - email: ${SUPPORT_MAIL_5_EMAIL}
        password: ${SUPPORT_MAIL_5_PASSWORD}
      - email: ${SUPPORT_MAIL_6_EMAIL}
        password: ${SUPPORT_MAIL_6_PASSWORD}
      - email: ${SUPPORT_MAIL_7_EMAIL}
        password: ${SUPPORT_MAIL_7_PASSWORD}
      - email: ${SUPPORT_MAIL_8_EMAIL}
        password: ${SUPPORT_MAIL_8_PASSWORD}
      - email: ${SUPPORT_MAIL_9_EMAIL}
        password: ${SUPPORT_MAIL_9_PASSWORD}
      - email: ${SUPPORT_MAIL_10_EMAIL}
        password: ${SUPPORT_MAIL_10_PASSWORD}




  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

app:
  # frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}
  frontend-url: ${APP_FRONTEND_URL:https://veaglespace.com}
  admin-emails:
    - singareakshay937@gmail.com
    - singareakshay2004@gmail.com

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

admin:
  secret: ${ADMIN_SECRET}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

server:
  port: 8080
