spring:
  application:
    name: VeagleSpaceTech

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/veagledb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Veagle@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:singareakshay2004@gmail.com}
    password: ${MAIL_PASS:rcckpmkrnkopufmv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

jwt:
  secret: ${JWT_SECRET:VeagleJwtSecretKey2026UltraSecure123!}

admin:
  secret: ${ADMIN_SECRET:admin123}

  # 🔹 CLOUDINARY (same as it is)
cloudinary:
  cloud-name: dbehhnhhi
  api-key: 266323574446942
  api-secret: jiEAtmhR144qAZFvZLIWDwsRrKA
