spring:
  application:
    name: VeagleSpaceTech

  datasource:
    # HOSTINGER VPS: Update these with your Hostinger MySQL credentials
    # Local dev: jdbc:mysql://localhost:3306/veagledb
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/veagledb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

veagle:
  mail:
    otp:
      - email: noreply@veaglespace.com
        password: Veagle@123
      - email: noreply1@veaglespace.com
        password: Veagle@123
      - email: noreply2@veaglespace.com
        password: Veagle@123

    careers:
      - email: careers@veaglespace.com
        password: Veagle@123
      - email: careers1@veaglespace.com
        password: Veagle@123
      - email: careers2@veaglespace.com
        password: Veagle@123
      - email: careers3@veaglespace.com
        password: Veagle@123

    support:
      - email: support@veaglespace.com
        password: Veagle@123
      - email: support1@veaglespace.com
        password: Veagle@123
      - email: support2@veaglespace.com
        password: Veagle@123
      - email: support3@veaglespace.com
        password: Veagle@123
      - email: support4@veaglespace.com
        password: Veagle@123
      - email: support5@veaglespace.com
        password: Veagle@123
      - email: support6@veaglespace.com
        password: Veagle@123
      - email: support7@veaglespace.com
        password: Veagle@123
      - email: support8@veaglespace.com
        password: Veagle@123
      - email: support9@veaglespace.com
        password: Veagle@123


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

app:
  frontend-url: http://localhost:3000  #Local Host APi
#  frontend-url: https://www.veaglespace.com  # Deployed APi

jwt:
  secret: ${JWT_SECRET:VeagleJwtSecretKey2026UltraSecure123!}

admin:
  secret: ${ADMIN_SECRET:admin123}

cloudinary:
  cloud-name: dbehhnhhi
  api-key: 266323574446942
  api-secret: jiEAtmhR144qAZFvZLIWDwsRrKA

server:
  port: 8080

