export const defaultContent = {
  hero: {
    label: "",
    title: "",
    highlight: "",
    description: "",
    primaryCtaLabel: "",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
  },
  stats: [],
  differentiators: [],
  process: [],
  testimonials: [],
  faq: [],
  finalCta: {
    title: "",
    description: "",
    primaryLabel: "",
    primaryHref: "",
    secondaryLabel: "",
    secondaryHref: "",
  },
  contact: {
    title: "",
    description: "",
    email: "",
    phone: "",
    address: "",
  },
  about: {
    eyebrow: "",
    title: "",
    description: "",
    story: "",
    background: "",
    milestones: [],
    pillars: [],
    workingModel: [],
    ctaTitle: "",
    ctaDescription: "",
  },
  clients: {
    eyebrow: "",
    title: "",
    description: "",
    logos: [],
    marquee: [],
    segments: [],
    proof: [],
    ctaTitle: "",
    ctaDescription: "",
  },
  career: {
    eyebrow: "",
    title: "",
    description: "",
    highlights: [],
    reasons: [],
    applyTitle: "",
    applyDescription: "",
  },
  servicesPage: {
    eyebrow: "",
    title: "",
    description: "",
    highlights: [],
    ctaTitle: "",
    ctaDescription: "",
  },
  productsPage: {
    eyebrow: "",
    title: "",
    description: "",
    highlights: [],
    ctaTitle: "",
    ctaDescription: "",
  },
  portfolio: {
    eyebrow: "",
    title: "",
    description: "",
    projects: [],
    ctaTitle: "",
    ctaDescription: "",
  },
  university: {
    eyebrow: "",
    title: "",
    description: "",
    chips: [],
    features: [],
    benefits: [],
    highlightTitle: "",
    highlightDescription: "",
  },
};
